### ISSUE TITLE
can't pip install torchsar

### ISSUE THREAD

**Issue by ZIWEN-LALA** [aisari/AutofocusSAR#1]
why i can't pip install torchsar,which has such error:
ERROR: Could not find a version that satisfies the requirement torchsar
ERROR: No matching distribution found for torchsar

**Comment by antsfamily** [comment]
You can download torchsar from https://pypi.org/project/torchsar/  and then install  by pip install torchsar-1.1.14.tar.gz

**Comment by antsfamily** [comment]
> why i can't pip install torchsar,which has such error: ERROR: Could not find a version that satisfies the requirement torchsar ERROR: No matching distribution found for torchsar

You can download torchsar from https://pypi.org/project/torchsar/ and then install by pip install torchsar-1.1.14.tar.gz
