### ISSUE TITLE
How to make a training set

### ISSUE THREAD

**Issue by Attractiveee** [aisari/AutofocusSAR#2]
Hello, I have just started to study SAR autofocusing. How can I get the defocus data for training here? How to add phase error to the image?

**Comment by antsfamily** [comment]
> Hello, I have just started to study SAR autofocusing. How can I get the defocus data for training here? How to add phase error to the image?

You can add phase error by the following formula

F(X)*exp(-j*phi), where phi is the phase error, X is the complex SAR image, F is FT or IFT, which depends on the imaging mode of SAR.

You can use our torchsar's defocus function to defocus images, see https://aisari.iridescent.ink/torchsar/torchsar.autofocus.html#module-torchsar.autofocus.focusing  for details.

> Hello, I have just started to study SAR autofocusing. How can I get the defocus data for training here? How to add phase error to the image?

You can add phase error by the following formula

F(X)*exp(-j*phi), where phi is the phase error, X is the complex SAR image, F is FT or IFT, which depends on the imaging mode of SAR.

You can use our torchsar's defocus function to defocus images, see https://aisari.iridescent.ink/torchsar/torchsar.autofocus.html#module-torchsar.autofocus.focusing  for details.

**Comment by antsfamily** [comment]
> Hello, I have just started to study SAR autofocusing. How can I get the defocus data for training here? How to add phase error to the image?

You can add phase error by the following formula

F(X)*exp(-j*phi), where phi is the phase error, X is the complex SAR image, F is FT or IFT, which depends on the imaging mode of SAR.

You can use our torchsar's defocus function to defocus images, see https://aisari.iridescent.ink/torchsar/torchsar.autofocus.html#module-torchsar.autofocus.focusing  for details.
