### ISSUE TITLE
数据集的SI内矩阵值如何得到的

### ISSUE THREAD

**Issue by leileiguo** [aisari/AutofocusSAR#3]
你好，请问一下数据集中SI内的散焦图片的矩阵是用灰度图得到的吗？是的话是用位深度为多少位得到的？

**Comment by aisari** [comment]
不是，SI是对原始SAR数据使用RDA算法成像后的结果，未进行后处理，直接显示可能是黑色的，这个正常，你可以使用本人开发的torchbox工具包里的mapping函数进行后处理显示，手册参见http://iridescent.ink/torchbox/torchbox.misc.html#torchbox.misc.mapping_operation.mapping
