### ISSUE TITLE
How to calculate `PSNR`, `SSIM`, `PSLR`, `ISLR`

### ISSUE THREAD

**Issue by PalgunaGopireddy** [aisari/AutofocusSAR#8]
In the paper [A FINELY FOCUSING METHOD OF SAR USING VERY DEEP NEURAL NETWORK ](https://ieeexplore.ieee.org/document/8898407) it is written as 

> To evaluate the effect of focusing, the Peak Signal-to-Noise Ratio (**PSNR**) and Structural Similarity Index (**SSIM**) of the whole image is used in this paper. Meanwhile, in order to evaluate the image effect, Peak Sidelobe Ratio (**PSLR**) and Integration Sidelobe Ratio (**ISLR**)  of kernel function are used.

But the repository's `VDNNAF` folder told to be a PyTorch implementation of this paper, doesn't have these terms defined.
Instead, it is printing a term called **entropy** , **contrast** while running `test.py`

THough you siad _`(implenmented by me, not the official).`_ do you know how to calclute these values and what does `entropy` abd `contrast` represent? and high value or low value of these represent good defocusing?

**Comment by antsfamily** [comment]
> In the paper [A FINELY FOCUSING METHOD OF SAR USING VERY DEEP NEURAL NETWORK ](https://ieeexplore.ieee.org/document/8898407) it is written as
> 
> > To evaluate the effect of focusing, the Peak Signal-to-Noise Ratio (**PSNR**) and Structural Similarity Index (**SSIM**) of the whole image is used in this paper. Meanwhile, in order to evaluate the image effect, Peak Sidelobe Ratio (**PSLR**) and Integration Sidelobe Ratio (**ISLR**)  of kernel function are used.
> 
> But the repository's `VDNNAF` folder told to be a PyTorch implementation of this paper, doesn't have these terms defined. Instead, it is printing a term called **entropy** , **contrast** while running `test.py`
> 
> THough you siad _`(implenmented by me, not the official).`_ do you know how to calclute these values and what does `entropy` abd `contrast` represent? and high value or low value of these represent good defocusing?

This paper is not our's, we didn't implement PSNR、SSIM、PSLR and ISLR. You can consult the authors to get code.

**Comment by PalgunaGopireddy** [comment]
Thanks. I will ask them.

what do the `entropy` and `contrast` represent that are printed after running `test.py`? also, high value or low value of these represent good defocusing?

**Comment by aisari** [comment]
Please see our paper：Fast SAR Autofocus Based on Ensemble Convolutional Extreme Learning Machine， https://doi.org/10.3390/rs13142683



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 12/08/2023 15:20 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [aisari/AutofocusSAR] How to calculate `PSNR`, `SSIM`, `PSLR`, `ISLR` (Issue #8) |

Thanks. I will ask them.

what do the entropy and contrast represent that are printed after running test.py? also, high value or low value of these represent good defocusing?
